const assert=require('node:assert/strict');
const {Game,LEVELS,dist}=require('./engine.js');
function readyGame(options={}){return new Game({prebuilt:true,startingMoney:150,...options});}
const tests=[];function test(name,fn){try{fn();tests.push({name,pass:true});}catch(e){tests.push({name,pass:false,error:e.message});}}
function advance(g,seconds){for(let i=0;i<Math.round(seconds*60);i++)g.step(1/60);}
test('First titan appears at 10 seconds, never earlier',()=>{const g=readyGame();advance(g,9.9);assert.equal(g.wave,0);advance(g,.1);assert.equal(g.wave,1);assert.equal(g.monsters[0].level,1);assert.equal(g.phase,'battle');});
test('Six live level-one walls earn 30 dollars per second',()=>{const g=readyGame();advance(g,10);assert.ok(Math.abs(g.money-450)<.001);g.walls[0].hp=0;assert.ok(Math.abs(g.income()-25)<.001);});
test('Shop requires proximity, money and an empty inventory',()=>{const g=readyGame();g.money=500;assert.equal(g.buy(2).ok,false);g.player={...g.shop};assert.equal(g.buy(2).ok,true);assert.equal(g.inventory,2);assert.equal(g.money,100);assert.equal(g.buy(2).ok,false);});
test('Installation upgrades one of six sections and consumes kit only at completion',()=>{const g=readyGame();g.inventory=2;g.player={...g.walls[0]};assert.equal(g.install(0).ok,true);advance(g,1);assert.equal(g.inventory,2);advance(g,1.1);assert.equal(g.inventory,null);assert.equal(g.walls[0].hp,600);assert.equal(g.walls.filter(w=>w.level===1).length,5);});
test('Attack lock blocks installation, including rubble',()=>{const g=readyGame();g.inventory=2;g.player={...g.walls[0]};g.walls[0].lastHit=g.time;assert.equal(g.install(0).ok,false);g.walls[0].hp=0;assert.equal(g.install(0).ok,false);});
test('Attack during installation preserves purchased kit',()=>{const g=readyGame();g.inventory=2;g.player={...g.walls[0]};g.install(0);advance(g,.5);g.walls[0].lastHit=g.time;advance(g,.1);assert.equal(g.job,null);assert.equal(g.inventory,2);assert.equal(g.walls[0].level,1);});
test('Moving cancels work without consuming kit',()=>{const g=readyGame();g.inventory=2;g.player={...g.walls[0]};g.install(0);g.step(.1,{x:1});assert.equal(g.job,null);assert.equal(g.inventory,2);});
test('Repair is paid, bounded by max HP, and allowed under attack',()=>{const g=readyGame();g.player={...g.walls[0]};g.walls[0].hp=100;g.walls[0].lastHit=0;assert.equal(g.repair(0).ok,true);advance(g,4.2);assert.equal(g.walls[0].hp,180);assert.ok(Math.abs(g.stats.spent-12)<.001);});
test('Destroyed walls require replacement and cannot be repaired',()=>{const g=readyGame();g.walls[0].hp=0;g.player={...g.walls[0]};assert.equal(g.repair(0).ok,false);});
test('Cannons kill titans and grant rewards',()=>{const g=readyGame();g.spawn();g.monsters[0].x=0;g.monsters[0].y=60;g.monsters[0].hp=1;advance(g,2);assert.equal(g.stats.kills,1);assert.ok(g.money>=230);});
test('A titan that breached does not walk back to a restored wall',()=>{const g=readyGame();g.spawn();const m=g.monsters[0],w=g.walls[m.target];w.hp=0;m.x=w.x;m.y=w.y+15;advance(g,.1);assert.equal(m.breached,true);w.hp=180;const y=m.y;advance(g,.5);assert.ok(m.y>y);});
test('City destruction ends simulation',()=>{const g=readyGame();g.core=1;g.spawn();g.monsters[0].breached=true;g.monsters[0].x=0;g.monsters[0].y=230;advance(g,.1);assert.equal(g.state,'lost');const t=g.time;advance(g,10);assert.equal(g.time,t);});
test('Wave six is final; clearing it produces a win',()=>{const g=readyGame();g.wave=6;g.nextWave=0;g.monsters=[];g.step(.1);assert.equal(g.wave,6);assert.equal(g.state,'won');});
test('Full refund preserves balance and clears kit',()=>{const g=readyGame();g.player={...g.shop};g.money=400;g.buy(2);assert.equal(g.refund().ok,true);assert.equal(g.money,400);assert.equal(g.inventory,null);});
test('Fixed-step simulation is reproducible',()=>{const a=readyGame(),b=readyGame();advance(a,400);advance(b,400);assert.deepEqual(a.export(),b.export());});
test('Six walls form a horizontal line ahead of the city',()=>{const g=readyGame();assert.equal(new Set(g.walls.map(w=>w.y)).size,1);assert.equal(new Set(g.walls.map(w=>w.x)).size,6);assert.ok(g.corePosition.y>g.walls[0].y);});
test('Direct upgrade charges the displayed price and changes only selected wall',()=>{const g=readyGame();g.money=400;assert.equal(g.upgrade(3).ok,true);assert.equal(g.money,0);assert.equal(g.walls[3].level,1);advance(g,1.9);assert.equal(g.walls[3].level,1);advance(g,.1);assert.equal(g.walls[3].level,2);assert.equal(g.walls[3].hp,600);assert.equal(g.walls.filter(w=>w.level===1).length,5);});
test('Insufficient resources cannot upgrade or spend funds',()=>{const g=readyGame();assert.equal(g.upgrade(3).ok,false);assert.equal(g.money,150);assert.equal(g.walls[3].level,1);});
test('An attacked wall blocks direct upgrade',()=>{const g=readyGame();g.money=500;g.spawn();const m=g.monsters[0],w=g.walls[m.target];m.x=w.x;m.y=w.y-40;assert.equal(g.upgrade(w.id).ok,false);assert.equal(g.money,500);});
test('Forecast is stable, targets spawn from above, and routes commit to one wall',()=>{const g=readyGame({seed:128});const plan=g.forecast();assert.deepEqual(g.forecast(),plan);g.spawn();const m=g.monsters[0];assert.equal(m.target,plan[0]);assert.ok(m.y<g.walls[m.target].y);advance(g,5);assert.equal(m.target,plan[0]);});
test('Seeds produce different attack plans without duplicate targets within a wave',()=>{const plans=Array.from({length:12},(_,i)=>readyGame({seed:i+1}).plans);assert.ok(new Set(plans.map(p=>JSON.stringify(p))).size>1);for(const p of plans)for(const wave of p)assert.equal(new Set(wave).size,wave.length);});
test('Destroyed wall can be restored at its current level',()=>{const g=readyGame();g.walls[2].hp=0;g.money=20;assert.equal(g.upgrade(2).ok,true);assert.equal(g.money,0);assert.equal(g.walls[2].hp,0);advance(g,2);assert.equal(g.walls[2].hp,180);});
test('A distant titan uses its selected gap before entering the city',()=>{const g=readyGame();g.spawn();const m=g.monsters[0];g.walls[m.target].hp=0;advance(g,1);assert.equal(!!m.breached,false);});
test('Player cannot cross the wall or leave the city, even through destroyed walls',()=>{const g=readyGame({firstWave:1000});g.walls.forEach(w=>w.hp=0);for(let i=0;i<600;i++)g.step(1/60,{x:0,y:-1});assert.equal(g.player.y,168);for(let i=0;i<600;i++)g.step(1/60,{x:1,y:1});assert.equal(g.player.x,290);assert.equal(g.player.y,310);});
test('Waves do not overlap while even one titan is still alive',()=>{const g=readyGame();g.spawn();const m=g.monsters[0];m.hp=1e9;m.damage=0;m.speed=0;advance(g,40);assert.equal(g.wave,1);assert.equal(g.phase,'battle');assert.equal(g.nextWave,null);});
test('Clearing a level starts exactly 10 seconds of preparation and keeps upgrades',()=>{const g=readyGame();g.money=500;g.upgrade(0);advance(g,2);g.spawn();g.monsters.forEach(m=>m.hp=0);g.step(1/60);assert.equal(g.phase,'prep');assert.ok(Math.abs(g.nextWave-g.time-10)<1e-8);assert.equal(g.walls[0].level,2);advance(g,9.9);assert.equal(g.wave,1);advance(g,.1);assert.equal(g.wave,2);assert.equal(g.phase,'battle');});
test('Preparation starts only after the last titan of a multi-titan level dies',()=>{const g=readyGame();g.wave=2;g.spawn();assert.equal(g.monsters.length,2);g.monsters[0].hp=0;g.monsters[1].hp=1e9;g.monsters[1].speed=0;g.step(1/60);assert.equal(g.phase,'battle');assert.equal(g.nextWave,null);g.monsters[0].hp=0;g.step(1/60);assert.equal(g.phase,'prep');});
test('Titans move slowly and approach their selected wall',()=>{const g=readyGame();g.spawn();const m=g.monsters[0],p={x:m.x,y:m.y};advance(g,1);assert.ok(Math.abs(dist(p,m)-8.25)<.01);assert.ok(m.y>p.y);});
test('Income is paid once per second with one five-dollar pulse per live wooden wall',()=>{const g=readyGame();advance(g,.9);assert.equal(g.money,150);assert.equal(g.incomePulses.length,0);advance(g,.1);assert.ok(Math.abs(g.money-180)<1e-7);assert.equal(g.incomePulses.length,1);assert.equal(g.incomePulses[0].sections.length,6);for(const s of g.incomePulses[0].sections)assert.ok(Math.abs(s.amount-5)<1e-7);});
test('Destroyed sections stop generating income and are absent from the next full payout',()=>{const g=readyGame();g.walls[2].hp=0;advance(g,1);assert.ok(Math.abs(g.money-175)<1e-7);assert.equal(g.incomePulses[0].sections.some(s=>s.id===2),false);});
test('Mid-second upgrade prorates income without losing or duplicating dollars',()=>{const g=readyGame();g.money=400;advance(g,.5);assert.equal(g.upgrade(0).ok,true);advance(g,.5);assert.equal(g.income(),30);assert.equal(g.walls[0].level,1);advance(g,2);assert.ok(Math.abs(g.money-92.5)<1e-7);assert.ok(Math.abs(g.incomePulses.at(-1).sections[0].amount-7.5)<1e-7);assert.equal(g.income(),35);});

test('Fresh game has six empty sites, 20 dollars, no income and no titan timer',()=>{const g=new Game();assert.equal(g.money,20);assert.equal(g.income(),0);assert.equal(g.builtCount(),0);assert.ok(g.walls.every(w=>!w.built&&w.hp===0));advance(g,60);assert.equal(g.money,20);assert.equal(g.wave,0);assert.equal(g.nextWave,null);});
test('Construction requires proximity and costs exactly 20 dollars',()=>{const g=new Game();assert.equal(g.construct(0).ok,false);g.player={x:g.walls[0].x,y:175};assert.equal(g.construct(0).ok,true);assert.equal(g.money,0);assert.equal(g.walls[0].hp,180);assert.equal(g.builtCount(),1);assert.equal(g.construct(0).ok,false);assert.equal(g.stats.spent,20);});
test('A first wall earns enough for the next wall in four seconds',()=>{const g=new Game();g.player={x:g.walls[0].x,y:175};g.construct(0);advance(g,3);assert.ok(Math.abs(g.money-15)<1e-7);g.player={x:g.walls[1].x,y:175};assert.equal(g.construct(1).ok,false);advance(g,1);assert.equal(g.construct(1).ok,true);assert.equal(g.income(),10);assert.equal(g.stats.builds,2);});
test('No upgrade or shop purchase can bypass six initial constructions',()=>{const g=new Game();g.money=1e4;g.player={x:g.walls[0].x,y:175};g.construct(0);assert.equal(g.upgrade(0).ok,false);g.player={...g.shop};assert.equal(g.buy(2).ok,false);g.inventory=2;g.player={x:g.walls[1].x,y:175};assert.equal(g.install(1).ok,false);assert.equal(g.walls[1].built,false);});
test('Sixth construction unlocks upgrades and starts exactly ten seconds of preparation',()=>{const g=new Game();g.money=2000;advance(g,45);for(let i=0;i<6;i++){g.player={x:g.walls[i].x,y:175};assert.equal(g.construct(i).ok,true);}assert.equal(g.income(),30);assert.equal(g.phase,'prep');assert.ok(Math.abs(g.nextWave-g.time-10)<1e-7);assert.equal(g.upgrade(0).ok,true);advance(g,9.9);assert.equal(g.wave,0);advance(g,.1);assert.equal(g.wave,1);});
test('Rebuilding a destroyed wall does not re-lock construction progression',()=>{const g=readyGame();g.walls[0].hp=0;assert.equal(g.builtCount(),6);assert.equal(g.construct(0).ok,false);assert.equal(g.upgrade(0).ok,true);assert.equal(g.builtCount(),6);});
test('All six sites are reachable from inside the city with normal movement',()=>{const g=new Game();g.money=200;for(const w of g.walls){const p={x:w.x,y:175};for(let i=0;i<300&&dist(g.player,p)>3;i++)g.step(1/60,{x:p.x-g.player.x,y:p.y-g.player.y});assert.ok(g.player.y>=168);assert.equal(g.construct(w.id).ok,true);}assert.equal(g.builtCount(),6);});

test('First payout is five dollars one full second after the first construction',()=>{const g=new Game();advance(g,.6);g.player={x:g.walls[0].x,y:175};g.construct(0);advance(g,.9);assert.equal(g.money,0);advance(g,.1);assert.ok(Math.abs(g.money-5)<1e-7);});

test('Every direct upgrade level waits two seconds and retains old stats until completion',()=>{const g=readyGame({firstWave:1000,startingMoney:1e5});for(let level=2;level<=5;level++){assert.equal(g.upgrade(0).ok,true);assert.equal(g.job.duration,2);advance(g,1.9);assert.equal(g.walls[0].level,level-1);assert.equal(g.income(),25+LEVELS[level-1].income);advance(g,.1);assert.equal(g.walls[0].level,level);assert.equal(g.walls[0].hp,LEVELS[level].hp);assert.equal(g.job,null);}assert.equal(g.stats.installs,4);});
test('Repeated upgrade clicks cannot restart timers or charge twice',()=>{const g=readyGame({startingMoney:2000});g.upgrade(0);advance(g,.5);const cost=g.stats.spent;assert.equal(g.upgrade(0).ok,false);assert.equal(g.upgrade(1).ok,false);assert.equal(g.job.id,0);assert.ok(Math.abs(g.job.t-.5)<1e-7);assert.equal(g.stats.spent,cost);});
test('Moving cancels a paid upgrade and refunds its full price',()=>{const g=readyGame({startingMoney:400});g.upgrade(0);advance(g,.5);g.step(.1,{x:1});assert.equal(g.job,null);assert.equal(g.money,400);assert.equal(g.stats.spent,0);assert.equal(g.walls[0].level,1);assert.equal(g.stats.installs,0);});
test('Attack interrupts direct upgrade with full refund and no change of level',()=>{const g=readyGame({startingMoney:400});g.upgrade(0);advance(g,.5);g.walls[0].lastHit=g.time;g.step(.1);assert.equal(g.job,null);assert.equal(g.money,400);assert.equal(g.walls[0].level,1);assert.equal(g.stats.installs,0);});
test('Cancelling through the shop cannot refund twice or remove an unrelated kit',()=>{const g=readyGame({startingMoney:400});g.inventory=3;g.upgrade(0);g.cancelJob();g.cancelJob();assert.equal(g.money,400);assert.equal(g.stats.spent,0);assert.equal(g.inventory,3);});
test('Completing a paid upgrade preserves a previously purchased kit',()=>{const g=readyGame({startingMoney:400});g.inventory=3;g.upgrade(0);advance(g,2);assert.equal(g.walls[0].level,2);assert.equal(g.inventory,3);assert.equal(g.stats.installs,1);assert.equal(g.stats.spent,400);});

console.log(JSON.stringify(tests,null,2));if(tests.some(t=>!t.pass))process.exitCode=1;
